name: orange_network
description: "Firestore functions for Networking."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_lints: ^2.0.0